onboarding = false

[keys]
prefix = "ctrl+space"
next_workspace = "ctrl+shift+right"
previous_workspace = "ctrl+shift+left"

[theme]
name = "dracula"
auto_switch = false

[ui]
status_indicators = "dots"
